source "https://rubygems.org"

gem "rails", "~> 8.0.2"
gem "propshaft"
gem "pg" # production database

# Web server
gem "puma", ">= 5.0"

# JavaScript and frontend
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bootstrap", "~> 5.3"
gem "font-awesome-sass", "~> 6.7"
gem "dartsass-rails"

# Optional utilities
gem "kamal", require: false
gem "thruster", require: false
gem "bootsnap", require: false

# Platform-specific
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "sqlite3", ">= 2.1"  # only used locally
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
