default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Keep SQLite for development and test if desired
development:
  adapter: sqlite3
  <<: *default
  database: storage/development.sqlite3

test:
  adapter: sqlite3
  <<: *default
  database: storage/test.sqlite3

# Simplified production configuration using SQLite temporarily
production:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000